INSERT INTO BOOKMANAGER.BOOKS (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('1', 'First Note', 'First Author', '30000');
INSERT INTO BOOKMANAGER.BOOKS (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('2', 'Second Note', 'Second Author', '20000');
INSERT INTO BOOKMANAGER.BOOKS (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('3', 'Third Note', 'Third Author', '15000');
INSERT INTO BOOKMANAGER.BOOKS (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('4', 'Fourth Note', 'Fourth Author', '25000');
INSERT INTO BOOKMANAGER.BOOKS (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('5', 'Fifth Note', 'Fifth Author', '80000');
INSERT INTO BOOKMANAGER.BOOKS (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('6', 'Sixth Note', 'Sixth Author', '50000');
